language: rust

matrix:
  include:
    - env: TARGET=thumbv7em-none-eabi

before_install: set -e

install:
  - sh ci/install.sh

script:
  - sh ci/script.sh

after_script: set +e

cache: cargo

branches:
  only:
    - auto
    - master
    - try

notifications:
  email:
    on_success: never
