[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
build = "build.rs"
name = "photon"
version = "0.1.0"

[build-dependencies]
tempdir = "0.3.4"

[dependencies.particle-hal]
git = "https://github.com/japaric/particle-hal"
